from hivelibrary.env import DB_BLOB_STORAGE,DB_SYSTEM_TABLE,DB_LOCAL_AUTHENTICATE_TABLE, DB_FACE_RECOGNITION_TABLE



DATABASE_STRUCTURE_COMMAND = f"""
CREATE TABLE IF NOT EXISTS {DB_SYSTEM_TABLE} (
    id INTEGER NOT NULL,
    uniq_key TEXT NOT NULL UNIQUE,
    value TEXT NOT NULL,
    PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS {DB_BLOB_STORAGE} (
    id INTEGER NOT NULL,
    unique_blob_key TEXT NOT NULL UNIQUE,
    key_value BLOB NOT NULL,
    data_type TEXT NOT NULL DEFAULT 'user',
    information_notes TEXT DEFAULT NULL,
    PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS {DB_LOCAL_AUTHENTICATE_TABLE} (
    id INTEGER NOT NULL,
    username TEXT(64) NOT NULL UNIQUE,
    password TEXT(64) NOT NULL,
    PRIMARY KEY("id")
);
"""


FACE_RECOGNITION_DATABASE_STRUCTUR_COMMAND = f"""
CREATE TABLE IF NOT EXISTS {DB_FACE_RECOGNITION_TABLE} (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    face_picture_blob BLOB NOT NULL, 
    picture_sha1_hash TEXT NOT NULL UNIQUE,
    face_embedding_data TEXT NOT NULL,
    landmarks_2d TEXT NOT NULL,
    face_box TEXT NOT NULL,
    face_name TEXT NOT NULL,
    raw_face_data TEXT NOT NULL,
    add_date DATETIME DEFAULT CURRENT_TIMESTAMP
);
"""