from hivelibrary.env import DB_BLOB_STORAGE,DB_SYSTEM_TABLE,DB_LOCAL_AUTHENTICATE_TABLE, DB_FACE_RECOGNITION_TABLE


POSTGRESQL_DATABASE_STRUCTURE = f"""
CREATE TABLE IF NOT EXISTS {DB_SYSTEM_TABLE} (
     id SERIAL PRIMARY KEY,
     unique_key VARCHAR(100) NOT NULL UNIQUE,
     value VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS {DB_BLOB_STORAGE} (
    id SERIAL PRIMARY KEY,
    unique_blob_key TEXT NOT NULL UNIQUE,
    key_value BYTEA NOT NULL,
    data_type TEXT NOT NULL DEFAULT 'user',
    information_notes TEXT DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS {DB_LOCAL_AUTHENTICATE_TABLE} (
    id SERIAL PRIMARY KEY,
    username VARCHAR(128) NOT NULL UNIQUE,
    password VARCHAR(128) NOT NULL
);
CREATE TABLE IF NOT EXISTS {DB_FACE_RECOGNITION_TABLE} (
    id SERIAL PRIMARY KEY,
    face_picture_blob BYTEA NOT NULL, 
    picture_sha1_hash TEXT NOT NULL UNIQUE,
    face_embedding_data BYTEA NOT NULL,
    landmarks_2d BYTEA NOT NULL,
    face_box BYTEA NOT NULL,
    face_name TEXT NOT NULL,
    add_date TIMESTAMP DEFAULT NOW()
);

"""













# OLD SQLITE STRUCTURE 

DATABASE_STRUCTURE_COMMAND_SQLITE = f"""
CREATE TABLE IF NOT EXISTS {DB_SYSTEM_TABLE} (
    id INTEGER NOT NULL,
    uniq_key TEXT NOT NULL UNIQUE,
    value TEXT NOT NULL,
    PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS {DB_BLOB_STORAGE} (
    id INTEGER NOT NULL,
    unique_blob_key TEXT NOT NULL UNIQUE,
    key_value BLOB NOT NULL,
    data_type TEXT NOT NULL DEFAULT 'user',
    information_notes TEXT DEFAULT NULL,
    PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS {DB_LOCAL_AUTHENTICATE_TABLE} (
    id INTEGER NOT NULL,
    username TEXT(64) NOT NULL UNIQUE,
    password TEXT(64) NOT NULL,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS {DB_FACE_RECOGNITION_TABLE} (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    face_picture_blob BLOB NOT NULL, 
    picture_sha1_hash TEXT NOT NULL UNIQUE,
    face_embedding_data BLOB NOT NULL,
    landmarks_2d BLOB NOT NULL,
    face_box BLOB NOT NULL,
    face_name TEXT NOT NULL,
    add_date DATETIME DEFAULT CURRENT_TIMESTAMP
);
"""



