from hivelibrary.env import DB_BLOB_STORAGE,DB_SYSTEM_TABLE,DB_LOCAL_AUTHENTICATE_TABLE, DATABASE_INIT_STATUS



DATABASE_STRUCTURE_COMMAND = f"""
CREATE TABLE IF NOT EXISTS {DB_SYSTEM_TABLE} (
    id INTEGER NOT NULL,
    uniq_key TEXT NOT NULL UNIQUE,
    value TEXT NOT NULL,
    PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS {DB_BLOB_STORAGE} (
    id INTEGER NOT NULL,
    unique_blob_key TEXT NOT NULL UNIQUE,
    key_value BLOB NOT NULL,
    data_type TEXT NOT NULL DEFAULT 'user',
    information_notes TEXT DEFAULT NULL,
    PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS {DB_LOCAL_AUTHENTICATE_TABLE} (
    id INTEGER NOT NULL,
    username TEXT(64) NOT NULL UNIQUE,
    password TEXT(64) NOT NULL,
    PRIMARY KEY("id")
);
"""