# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raw_ui_files/BinLookupScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BIN_LOOKUP_WIDGET(object):
    def setupUi(self, BIN_LOOKUP_WIDGET):
        BIN_LOOKUP_WIDGET.setObjectName("BIN_LOOKUP_WIDGET")
        BIN_LOOKUP_WIDGET.resize(795, 476)
        self.gridLayout = QtWidgets.QGridLayout(BIN_LOOKUP_WIDGET)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_start = QtWidgets.QPushButton(BIN_LOOKUP_WIDGET)
        self.pushButton_start.setObjectName("pushButton_start")
        self.gridLayout.addWidget(self.pushButton_start, 1, 2, 1, 1)
        self.lineEdit_bin_input = QtWidgets.QLineEdit(BIN_LOOKUP_WIDGET)
        self.lineEdit_bin_input.setMaximumSize(QtCore.QSize(351, 16777215))
        self.lineEdit_bin_input.setObjectName("lineEdit_bin_input")
        self.gridLayout.addWidget(self.lineEdit_bin_input, 1, 1, 1, 1)
        self.textBrowser_logConsole = QtWidgets.QTextBrowser(BIN_LOOKUP_WIDGET)
        self.textBrowser_logConsole.setMinimumSize(QtCore.QSize(0, 301))
        self.textBrowser_logConsole.setObjectName("textBrowser_logConsole")
        self.gridLayout.addWidget(self.textBrowser_logConsole, 2, 0, 1, 4)
        self.pushButton_clear = QtWidgets.QPushButton(BIN_LOOKUP_WIDGET)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.gridLayout.addWidget(self.pushButton_clear, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(BIN_LOOKUP_WIDGET)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(BIN_LOOKUP_WIDGET)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)

        self.retranslateUi(BIN_LOOKUP_WIDGET)
        QtCore.QMetaObject.connectSlotsByName(BIN_LOOKUP_WIDGET)

    def retranslateUi(self, BIN_LOOKUP_WIDGET):
        _translate = QtCore.QCoreApplication.translate
        BIN_LOOKUP_WIDGET.setWindowTitle(_translate("BIN_LOOKUP_WIDGET", "Form"))
        self.pushButton_start.setText(_translate("BIN_LOOKUP_WIDGET", "start"))
        self.pushButton_clear.setText(_translate("BIN_LOOKUP_WIDGET", "clear"))
        self.label_2.setText(_translate("BIN_LOOKUP_WIDGET", "Target BIN:"))
        self.label.setText(_translate("BIN_LOOKUP_WIDGET", "<html><head/><body><p align=\"center\">BIN Lookup</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BIN_LOOKUP_WIDGET = QtWidgets.QWidget()
    ui = Ui_BIN_LOOKUP_WIDGET()
    ui.setupUi(BIN_LOOKUP_WIDGET)
    BIN_LOOKUP_WIDGET.show()
    sys.exit(app.exec_())
