# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raw_ui_files/changePassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_changePassword(object):
    def setupUi(self, changePassword):
        changePassword.setObjectName("changePassword")
        changePassword.resize(479, 380)
        changePassword.setMinimumSize(QtCore.QSize(479, 380))
        changePassword.setMaximumSize(QtCore.QSize(479, 380))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/private_icon/private_logo_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        changePassword.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(changePassword)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_newPasswordConfirm_input = QtWidgets.QLineEdit(changePassword)
        self.lineEdit_newPasswordConfirm_input.setMinimumSize(QtCore.QSize(461, 31))
        self.lineEdit_newPasswordConfirm_input.setMaximumSize(QtCore.QSize(461, 31))
        self.lineEdit_newPasswordConfirm_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_newPasswordConfirm_input.setObjectName("lineEdit_newPasswordConfirm_input")
        self.gridLayout.addWidget(self.lineEdit_newPasswordConfirm_input, 8, 0, 1, 3)
        self.lineEdit_oldPassword_input = QtWidgets.QLineEdit(changePassword)
        self.lineEdit_oldPassword_input.setMinimumSize(QtCore.QSize(461, 31))
        self.lineEdit_oldPassword_input.setMaximumSize(QtCore.QSize(461, 31))
        self.lineEdit_oldPassword_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_oldPassword_input.setObjectName("lineEdit_oldPassword_input")
        self.gridLayout.addWidget(self.lineEdit_oldPassword_input, 4, 0, 1, 3)
        self.label_changeStatusBar = QtWidgets.QLabel(changePassword)
        self.label_changeStatusBar.setMinimumSize(QtCore.QSize(451, 31))
        self.label_changeStatusBar.setStyleSheet("font: 12pt \"FreeMono\";")
        self.label_changeStatusBar.setObjectName("label_changeStatusBar")
        self.gridLayout.addWidget(self.label_changeStatusBar, 10, 0, 1, 3)
        self.label_3 = QtWidgets.QLabel(changePassword)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.lineEdit_newPassword_input = QtWidgets.QLineEdit(changePassword)
        self.lineEdit_newPassword_input.setMinimumSize(QtCore.QSize(461, 31))
        self.lineEdit_newPassword_input.setMaximumSize(QtCore.QSize(461, 31))
        self.lineEdit_newPassword_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_newPassword_input.setObjectName("lineEdit_newPassword_input")
        self.gridLayout.addWidget(self.lineEdit_newPassword_input, 6, 0, 1, 3)
        self.pushButton_runChange = QtWidgets.QPushButton(changePassword)
        self.pushButton_runChange.setMinimumSize(QtCore.QSize(211, 41))
        self.pushButton_runChange.setMaximumSize(QtCore.QSize(211, 41))
        self.pushButton_runChange.setStyleSheet("font: 14pt \"Hack\";")
        self.pushButton_runChange.setObjectName("pushButton_runChange")
        self.gridLayout.addWidget(self.pushButton_runChange, 9, 0, 1, 2)
        self.pushButton_cancelChangeProccess = QtWidgets.QPushButton(changePassword)
        self.pushButton_cancelChangeProccess.setMinimumSize(QtCore.QSize(211, 41))
        self.pushButton_cancelChangeProccess.setMaximumSize(QtCore.QSize(211, 41))
        self.pushButton_cancelChangeProccess.setStyleSheet("font: 14pt \"Hack\";")
        self.pushButton_cancelChangeProccess.setObjectName("pushButton_cancelChangeProccess")
        self.gridLayout.addWidget(self.pushButton_cancelChangeProccess, 9, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(changePassword)
        self.label_2.setMaximumSize(QtCore.QSize(461, 36))
        self.label_2.setStyleSheet("font: 11pt \"Hack\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 3)
        self.label = QtWidgets.QLabel(changePassword)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(changePassword)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(changePassword)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEdit_username_input = QtWidgets.QLineEdit(changePassword)
        self.lineEdit_username_input.setMinimumSize(QtCore.QSize(461, 31))
        self.lineEdit_username_input.setMaximumSize(QtCore.QSize(461, 31))
        self.lineEdit_username_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_username_input.setObjectName("lineEdit_username_input")
        self.gridLayout.addWidget(self.lineEdit_username_input, 2, 0, 1, 1)

        self.retranslateUi(changePassword)
        QtCore.QMetaObject.connectSlotsByName(changePassword)

    def retranslateUi(self, changePassword):
        _translate = QtCore.QCoreApplication.translate
        changePassword.setWindowTitle(_translate("changePassword", "Form"))
        self.label_changeStatusBar.setText(_translate("changePassword", "Status:"))
        self.label_3.setText(_translate("changePassword", "NEW PASSWORD:"))
        self.pushButton_runChange.setText(_translate("changePassword", "change password"))
        self.pushButton_cancelChangeProccess.setText(_translate("changePassword", "canlcel proccess"))
        self.label_2.setText(_translate("changePassword", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Change Login Password</span></p></body></html>"))
        self.label.setText(_translate("changePassword", "OLD PASSWORD:"))
        self.label_4.setText(_translate("changePassword", "CONFIRM NEW PASSWORD:"))
        self.label_5.setText(_translate("changePassword", "USERNAME:"))
import main_icon_files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    changePassword = QtWidgets.QWidget()
    ui = Ui_changePassword()
    ui.setupUi(changePassword)
    changePassword.show()
    sys.exit(app.exec_())
