# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raw_ui_files/FaceRecognitionScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FaceRecognitionWidget(object):
    def setupUi(self, FaceRecognitionWidget):
        FaceRecognitionWidget.setObjectName("FaceRecognitionWidget")
        FaceRecognitionWidget.resize(1165, 763)
        self.gridLayout_4 = QtWidgets.QGridLayout(FaceRecognitionWidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_sourceImage = QtWidgets.QWidget(FaceRecognitionWidget)
        self.widget_sourceImage.setMinimumSize(QtCore.QSize(320, 320))
        self.widget_sourceImage.setObjectName("widget_sourceImage")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_sourceImage)
        self.gridLayout.setObjectName("gridLayout")
        self.label_soruceImageShower = QtWidgets.QLabel(self.widget_sourceImage)
        self.label_soruceImageShower.setMinimumSize(QtCore.QSize(320, 320))
        self.label_soruceImageShower.setText("")
        self.label_soruceImageShower.setObjectName("label_soruceImageShower")
        self.gridLayout.addWidget(self.label_soruceImageShower, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_sourceImage, 0, 0, 1, 1)
        self.widget_decetedImage = QtWidgets.QWidget(FaceRecognitionWidget)
        self.widget_decetedImage.setMinimumSize(QtCore.QSize(320, 320))
        self.widget_decetedImage.setObjectName("widget_decetedImage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_decetedImage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_detectedImageShower = QtWidgets.QLabel(self.widget_decetedImage)
        self.label_detectedImageShower.setMinimumSize(QtCore.QSize(320, 320))
        self.label_detectedImageShower.setText("")
        self.label_detectedImageShower.setObjectName("label_detectedImageShower")
        self.gridLayout_2.addWidget(self.label_detectedImageShower, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_decetedImage, 0, 1, 1, 1)
        self.widget = QtWidgets.QWidget(FaceRecognitionWidget)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.progressBar_benzerlikBari = QtWidgets.QProgressBar(self.widget)
        self.progressBar_benzerlikBari.setProperty("value", 0)
        self.progressBar_benzerlikBari.setObjectName("progressBar_benzerlikBari")
        self.gridLayout_3.addWidget(self.progressBar_benzerlikBari, 1, 3, 1, 2)
        self.pushButton_selectSourceImage = QtWidgets.QPushButton(self.widget)
        self.pushButton_selectSourceImage.setObjectName("pushButton_selectSourceImage")
        self.gridLayout_3.addWidget(self.pushButton_selectSourceImage, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        self.pushButton_startDbSearch = QtWidgets.QPushButton(self.widget)
        self.pushButton_startDbSearch.setObjectName("pushButton_startDbSearch")
        self.gridLayout_3.addWidget(self.pushButton_startDbSearch, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 1, 1, 2)
        self.pushButton_removeSourceImage = QtWidgets.QPushButton(self.widget)
        self.pushButton_removeSourceImage.setObjectName("pushButton_removeSourceImage")
        self.gridLayout_3.addWidget(self.pushButton_removeSourceImage, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 4, 1, 1)
        self.gridLayout_4.addWidget(self.widget, 1, 0, 1, 2)
        self.textBrowser_logConsole = QtWidgets.QTextBrowser(FaceRecognitionWidget)
        self.textBrowser_logConsole.setObjectName("textBrowser_logConsole")
        self.gridLayout_4.addWidget(self.textBrowser_logConsole, 2, 0, 1, 2)

        self.retranslateUi(FaceRecognitionWidget)
        QtCore.QMetaObject.connectSlotsByName(FaceRecognitionWidget)

    def retranslateUi(self, FaceRecognitionWidget):
        _translate = QtCore.QCoreApplication.translate
        FaceRecognitionWidget.setWindowTitle(_translate("FaceRecognitionWidget", "Form"))
        self.pushButton_selectSourceImage.setText(_translate("FaceRecognitionWidget", "Select"))
        self.pushButton_startDbSearch.setText(_translate("FaceRecognitionWidget", "Start Database Search"))
        self.label.setText(_translate("FaceRecognitionWidget", "Eşleşme Benzerlik:"))
        self.pushButton_removeSourceImage.setText(_translate("FaceRecognitionWidget", "Remove"))
        self.textBrowser_logConsole.setHtml(_translate("FaceRecognitionWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">LOG AND RESULTS:</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FaceRecognitionWidget = QtWidgets.QWidget()
    ui = Ui_FaceRecognitionWidget()
    ui.setupUi(FaceRecognitionWidget)
    FaceRecognitionWidget.show()
    sys.exit(app.exec_())
