# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raw_ui_files/FaceVerificationScreen_from_image.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FaceVerificationWidget(object):
    def setupUi(self, FaceVerificationWidget):
        FaceVerificationWidget.setObjectName("FaceVerificationWidget")
        FaceVerificationWidget.resize(1206, 816)
        self.gridLayout = QtWidgets.QGridLayout(FaceVerificationWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_5 = QtWidgets.QWidget(FaceVerificationWidget)
        self.widget_5.setMinimumSize(QtCore.QSize(1179, 119))
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_3 = QtWidgets.QLabel(self.widget_5)
        self.label_3.setStyleSheet("font: 12pt \"Hack\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 1, 3, 1, 1)
        self.comboBox_detectionModelSelecter = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_detectionModelSelecter.setStyleSheet("font: 12pt \"Hack\";")
        self.comboBox_detectionModelSelecter.setObjectName("comboBox_detectionModelSelecter")
        self.gridLayout_6.addWidget(self.comboBox_detectionModelSelecter, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_5)
        self.label.setStyleSheet("font: 12pt \"Hack\";")
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_verificationModelSelecter = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_verificationModelSelecter.setStyleSheet("font: 12pt \"Hack\";")
        self.comboBox_verificationModelSelecter.setObjectName("comboBox_verificationModelSelecter")
        self.gridLayout_6.addWidget(self.comboBox_verificationModelSelecter, 1, 1, 1, 1)
        self.pushButton_startVerification = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_startVerification.setObjectName("pushButton_startVerification")
        self.gridLayout_6.addWidget(self.pushButton_startVerification, 0, 3, 1, 1)
        self.progressBar_similarityBar = QtWidgets.QProgressBar(self.widget_5)
        self.progressBar_similarityBar.setProperty("value", 0)
        self.progressBar_similarityBar.setObjectName("progressBar_similarityBar")
        self.gridLayout_6.addWidget(self.progressBar_similarityBar, 1, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_5)
        self.label_2.setStyleSheet("font: 12pt \"Hack\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.widget_5, 3, 0, 1, 3)
        self.line = QtWidgets.QFrame(FaceVerificationWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 3, 1, 1)
        self.textBrowser_logConsole = QtWidgets.QTextBrowser(FaceVerificationWidget)
        self.textBrowser_logConsole.setStyleSheet("font: 12pt \"Hack\";")
        self.textBrowser_logConsole.setObjectName("textBrowser_logConsole")
        self.gridLayout.addWidget(self.textBrowser_logConsole, 4, 0, 1, 3)
        self.line_2 = QtWidgets.QFrame(FaceVerificationWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 5, 0, 1, 4)
        self.widget_4 = QtWidgets.QWidget(FaceVerificationWidget)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_removeSourceImage = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_removeSourceImage.setStyleSheet("font: 12pt \"Hack\";")
        self.pushButton_removeSourceImage.setObjectName("pushButton_removeSourceImage")
        self.gridLayout_5.addWidget(self.pushButton_removeSourceImage, 0, 2, 1, 1)
        self.pushButton_removeTargetImage = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_removeTargetImage.setStyleSheet("font: 12pt \"Hack\";")
        self.pushButton_removeTargetImage.setObjectName("pushButton_removeTargetImage")
        self.gridLayout_5.addWidget(self.pushButton_removeTargetImage, 0, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 3, 1, 1)
        self.pushButton_selectTargetImage = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_selectTargetImage.setStyleSheet("font: 12pt \"Hack\";")
        self.pushButton_selectTargetImage.setObjectName("pushButton_selectTargetImage")
        self.gridLayout_5.addWidget(self.pushButton_selectTargetImage, 0, 4, 1, 1)
        self.pushButton_selectSourceImage = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_selectSourceImage.setStyleSheet("font: 12pt \"Hack\";")
        self.pushButton_selectSourceImage.setObjectName("pushButton_selectSourceImage")
        self.gridLayout_5.addWidget(self.pushButton_selectSourceImage, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.widget_4, 2, 0, 1, 3)
        self.widget = QtWidgets.QWidget(FaceVerificationWidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 500))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_sourceImage = QtWidgets.QLabel(self.widget)
        self.label_sourceImage.setObjectName("label_sourceImage")
        self.gridLayout_2.addWidget(self.label_sourceImage, 0, 0, 1, 1)
        self.label_targetImage = QtWidgets.QLabel(self.widget)
        self.label_targetImage.setObjectName("label_targetImage")
        self.gridLayout_2.addWidget(self.label_targetImage, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 2, 4)

        self.retranslateUi(FaceVerificationWidget)
        QtCore.QMetaObject.connectSlotsByName(FaceVerificationWidget)

    def retranslateUi(self, FaceVerificationWidget):
        _translate = QtCore.QCoreApplication.translate
        FaceVerificationWidget.setWindowTitle(_translate("FaceVerificationWidget", "Form"))
        self.label_3.setText(_translate("FaceVerificationWidget", "Benzerlik Oranı:"))
        self.label.setText(_translate("FaceVerificationWidget", "Tespit Modeli:"))
        self.pushButton_startVerification.setText(_translate("FaceVerificationWidget", "Start Proccess"))
        self.label_2.setText(_translate("FaceVerificationWidget", "Doğrılama Modeli:"))
        self.textBrowser_logConsole.setHtml(_translate("FaceVerificationWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Hack\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:600;\">LOG CONSOLE:</span></p></body></html>"))
        self.pushButton_removeSourceImage.setText(_translate("FaceVerificationWidget", "remove image"))
        self.pushButton_removeTargetImage.setText(_translate("FaceVerificationWidget", "remove image"))
        self.pushButton_selectTargetImage.setText(_translate("FaceVerificationWidget", "select image"))
        self.pushButton_selectSourceImage.setText(_translate("FaceVerificationWidget", "select image"))
        self.label_sourceImage.setText(_translate("FaceVerificationWidget", "TextLabel"))
        self.label_targetImage.setText(_translate("FaceVerificationWidget", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FaceVerificationWidget = QtWidgets.QWidget()
    ui = Ui_FaceVerificationWidget()
    ui.setupUi(FaceVerificationWidget)
    FaceVerificationWidget.show()
    sys.exit(app.exec_())
