# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raw_ui_files/FaceVerificationScreen_from_image.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FaceVerificationWidget(object):
    def setupUi(self, FaceVerificationWidget):
        FaceVerificationWidget.setObjectName("FaceVerificationWidget")
        FaceVerificationWidget.resize(1206, 775)
        self.gridLayout_3 = QtWidgets.QGridLayout(FaceVerificationWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textBrowser_logConsole = QtWidgets.QTextBrowser(FaceVerificationWidget)
        self.textBrowser_logConsole.setMinimumSize(QtCore.QSize(0, 101))
        self.textBrowser_logConsole.setStyleSheet("font: 11pt \"Hack\";")
        self.textBrowser_logConsole.setObjectName("textBrowser_logConsole")
        self.gridLayout_3.addWidget(self.textBrowser_logConsole, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 5, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(FaceVerificationWidget)
        self.widget_5.setMinimumSize(QtCore.QSize(1179, 119))
        self.widget_5.setObjectName("widget_5")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.widget_5)
        self.label_3.setStyleSheet("font: 11pt \"Hack\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.progressBar_similarityBar = QtWidgets.QProgressBar(self.widget_5)
        self.progressBar_similarityBar.setMinimumSize(QtCore.QSize(471, 0))
        self.progressBar_similarityBar.setMaximumSize(QtCore.QSize(471, 16777215))
        self.progressBar_similarityBar.setProperty("value", 0)
        self.progressBar_similarityBar.setObjectName("progressBar_similarityBar")
        self.gridLayout.addWidget(self.progressBar_similarityBar, 0, 1, 1, 1)
        self.pushButton_startVerification = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_startVerification.setStyleSheet("font: 11pt \"Hack\";")
        self.pushButton_startVerification.setObjectName("pushButton_startVerification")
        self.gridLayout.addWidget(self.pushButton_startVerification, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)
        self.gridLayout_3.addWidget(self.widget_5, 2, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(FaceVerificationWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 6, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(FaceVerificationWidget)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_removeSourceImage = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_removeSourceImage.setStyleSheet("font: 11pt \"Hack\";")
        self.pushButton_removeSourceImage.setObjectName("pushButton_removeSourceImage")
        self.gridLayout_5.addWidget(self.pushButton_removeSourceImage, 0, 2, 1, 1)
        self.pushButton_removeTargetImage = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_removeTargetImage.setStyleSheet("font: 11pt \"Hack\";")
        self.pushButton_removeTargetImage.setObjectName("pushButton_removeTargetImage")
        self.gridLayout_5.addWidget(self.pushButton_removeTargetImage, 0, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 3, 1, 1)
        self.pushButton_selectTargetImage = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_selectTargetImage.setStyleSheet("font: 11pt \"Hack\";")
        self.pushButton_selectTargetImage.setObjectName("pushButton_selectTargetImage")
        self.gridLayout_5.addWidget(self.pushButton_selectTargetImage, 0, 4, 1, 1)
        self.pushButton_selectSourceImage = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_selectSourceImage.setStyleSheet("font: 11pt \"Hack\";")
        self.pushButton_selectSourceImage.setObjectName("pushButton_selectSourceImage")
        self.gridLayout_5.addWidget(self.pushButton_selectSourceImage, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget_4, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(FaceVerificationWidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 500))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_sourceImage = QtWidgets.QLabel(self.widget)
        self.label_sourceImage.setObjectName("label_sourceImage")
        self.gridLayout_2.addWidget(self.label_sourceImage, 0, 0, 1, 1)
        self.label_targetImage = QtWidgets.QLabel(self.widget)
        self.label_targetImage.setObjectName("label_targetImage")
        self.gridLayout_2.addWidget(self.label_targetImage, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 4, 0, 1, 1)

        self.retranslateUi(FaceVerificationWidget)
        QtCore.QMetaObject.connectSlotsByName(FaceVerificationWidget)

    def retranslateUi(self, FaceVerificationWidget):
        _translate = QtCore.QCoreApplication.translate
        FaceVerificationWidget.setWindowTitle(_translate("FaceVerificationWidget", "Form"))
        self.textBrowser_logConsole.setHtml(_translate("FaceVerificationWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Hack\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\'; font-weight:600;\">LOG CONSOLE:</span></p></body></html>"))
        self.label_3.setText(_translate("FaceVerificationWidget", "Benzerlik Oranı:"))
        self.pushButton_startVerification.setText(_translate("FaceVerificationWidget", "Start Proccess"))
        self.pushButton_removeSourceImage.setText(_translate("FaceVerificationWidget", "remove image"))
        self.pushButton_removeTargetImage.setText(_translate("FaceVerificationWidget", "remove image"))
        self.pushButton_selectTargetImage.setText(_translate("FaceVerificationWidget", "select image"))
        self.pushButton_selectSourceImage.setText(_translate("FaceVerificationWidget", "select image"))
        self.label_sourceImage.setText(_translate("FaceVerificationWidget", "TextLabel"))
        self.label_targetImage.setText(_translate("FaceVerificationWidget", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FaceVerificationWidget = QtWidgets.QWidget()
    ui = Ui_FaceVerificationWidget()
    ui.setupUi(FaceVerificationWidget)
    FaceVerificationWidget.show()
    sys.exit(app.exec_())
