# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raw_ui_files/HtsAnalaysisScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HTSanalaysis(object):
    def setupUi(self, HTSanalaysis):
        HTSanalaysis.setObjectName("HTSanalaysis")
        HTSanalaysis.resize(974, 714)
        self.centralwidget = QtWidgets.QWidget(HTSanalaysis)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 30, 911, 261))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_2.setMinimumSize(QtCore.QSize(550, 31))
        self.textBrowser_2.setMaximumSize(QtCore.QSize(550, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout.addWidget(self.textBrowser_2, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setMinimumSize(QtCore.QSize(550, 31))
        self.textBrowser.setMaximumSize(QtCore.QSize(550, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 1, 1, 1)
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_4.setMinimumSize(QtCore.QSize(550, 31))
        self.textBrowser_4.setMaximumSize(QtCore.QSize(550, 31))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.gridLayout.addWidget(self.textBrowser_4, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_3.setMinimumSize(QtCore.QSize(550, 31))
        self.textBrowser_3.setMaximumSize(QtCore.QSize(550, 31))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.gridLayout.addWidget(self.textBrowser_3, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        HTSanalaysis.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HTSanalaysis)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 974, 24))
        self.menubar.setObjectName("menubar")
        self.menuDosya_A = QtWidgets.QMenu(self.menubar)
        self.menuDosya_A.setObjectName("menuDosya_A")
        self.menuBilgi = QtWidgets.QMenu(self.menubar)
        self.menuBilgi.setObjectName("menuBilgi")
        HTSanalaysis.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HTSanalaysis)
        self.statusbar.setObjectName("statusbar")
        HTSanalaysis.setStatusBar(self.statusbar)
        self.actionDosya_A = QtWidgets.QAction(HTSanalaysis)
        self.actionDosya_A.setObjectName("actionDosya_A")
        self.actionBu_format_nedir = QtWidgets.QAction(HTSanalaysis)
        self.actionBu_format_nedir.setObjectName("actionBu_format_nedir")
        self.actionExcel_Dosyas = QtWidgets.QAction(HTSanalaysis)
        self.actionExcel_Dosyas.setObjectName("actionExcel_Dosyas")
        self.actionDesteklenen_Formatlar = QtWidgets.QAction(HTSanalaysis)
        self.actionDesteklenen_Formatlar.setObjectName("actionDesteklenen_Formatlar")
        self.menuDosya_A.addAction(self.actionExcel_Dosyas)
        self.menuBilgi.addAction(self.actionDesteklenen_Formatlar)
        self.menubar.addAction(self.menuDosya_A.menuAction())
        self.menubar.addAction(self.menuBilgi.menuAction())

        self.retranslateUi(HTSanalaysis)
        QtCore.QMetaObject.connectSlotsByName(HTSanalaysis)

    def retranslateUi(self, HTSanalaysis):
        _translate = QtCore.QCoreApplication.translate
        HTSanalaysis.setWindowTitle(_translate("HTSanalaysis", "MainWindow"))
        self.label_2.setText(_translate("HTSanalaysis", "Boyutu:"))
        self.label_4.setText(_translate("HTSanalaysis", "sha1 has\'i"))
        self.label.setText(_translate("HTSanalaysis", "Dosya Yolu:"))
        self.label_3.setText(_translate("HTSanalaysis", "Formatı:"))
        self.menuDosya_A.setTitle(_translate("HTSanalaysis", "Dosya Aç"))
        self.menuBilgi.setTitle(_translate("HTSanalaysis", "Bilgi"))
        self.actionDosya_A.setText(_translate("HTSanalaysis", "Dosya Aç"))
        self.actionBu_format_nedir.setText(_translate("HTSanalaysis", "Bu format nedir?"))
        self.actionExcel_Dosyas.setText(_translate("HTSanalaysis", "Excel Dosyası"))
        self.actionDesteklenen_Formatlar.setText(_translate("HTSanalaysis", "Desteklenen Formatlar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HTSanalaysis = QtWidgets.QMainWindow()
    ui = Ui_HTSanalaysis()
    ui.setupUi(HTSanalaysis)
    HTSanalaysis.show()
    sys.exit(app.exec_())
