# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raw_ui_files/StaticIPtracerScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IPTracerWidget_ipinfoio(object):
    def setupUi(self, IPTracerWidget_ipinfoio):
        IPTracerWidget_ipinfoio.setObjectName("IPTracerWidget_ipinfoio")
        IPTracerWidget_ipinfoio.resize(866, 514)
        self.gridLayout_2 = QtWidgets.QGridLayout(IPTracerWidget_ipinfoio)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(IPTracerWidget_ipinfoio)
        self.widget.setMinimumSize(QtCore.QSize(391, 0))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_ipInput = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_ipInput.setObjectName("lineEdit_ipInput")
        self.gridLayout.addWidget(self.lineEdit_ipInput, 2, 0, 1, 2)
        self.pushButton_startQuery = QtWidgets.QPushButton(self.widget)
        self.pushButton_startQuery.setObjectName("pushButton_startQuery")
        self.gridLayout.addWidget(self.pushButton_startQuery, 3, 0, 1, 1)
        self.pushButton_clearResults = QtWidgets.QPushButton(self.widget)
        self.pushButton_clearResults.setObjectName("pushButton_clearResults")
        self.gridLayout.addWidget(self.pushButton_clearResults, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 1, 1, 1)
        self.textBrowser_logConsole = QtWidgets.QTextBrowser(IPTracerWidget_ipinfoio)
        self.textBrowser_logConsole.setObjectName("textBrowser_logConsole")
        self.gridLayout_2.addWidget(self.textBrowser_logConsole, 1, 1, 1, 1)
        self.webView_mapView = QtWebEngineWidgets.QWebEngineView(IPTracerWidget_ipinfoio)
        self.webView_mapView.setMinimumSize(QtCore.QSize(400, 0))
        self.webView_mapView.setUrl(QtCore.QUrl("about:blank"))
        self.webView_mapView.setObjectName("webView_mapView")
        self.gridLayout_2.addWidget(self.webView_mapView, 0, 0, 2, 1)

        self.retranslateUi(IPTracerWidget_ipinfoio)
        QtCore.QMetaObject.connectSlotsByName(IPTracerWidget_ipinfoio)

    def retranslateUi(self, IPTracerWidget_ipinfoio):
        _translate = QtCore.QCoreApplication.translate
        IPTracerWidget_ipinfoio.setWindowTitle(_translate("IPTracerWidget_ipinfoio", "Form"))
        self.label.setText(_translate("IPTracerWidget_ipinfoio", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">IP Tracer | ipinfo.io</span></p></body></html>"))
        self.label_2.setText(_translate("IPTracerWidget_ipinfoio", "Target IP:"))
        self.pushButton_startQuery.setText(_translate("IPTracerWidget_ipinfoio", "Start"))
        self.pushButton_clearResults.setText(_translate("IPTracerWidget_ipinfoio", "Clear"))
from PyQt5 import QtWebEngineWidgets


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IPTracerWidget_ipinfoio = QtWidgets.QWidget()
    ui = Ui_IPTracerWidget_ipinfoio()
    ui.setupUi(IPTracerWidget_ipinfoio)
    IPTracerWidget_ipinfoio.show()
    sys.exit(app.exec_())
