# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raw_ui_files/MatplotShowScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MatplotShow(object):
    def setupUi(self, MatplotShow):
        MatplotShow.setObjectName("MatplotShow")
        MatplotShow.resize(908, 507)
        self.gridLayout = QtWidgets.QGridLayout(MatplotShow)
        self.gridLayout.setObjectName("gridLayout")
        self.plt_shower_widget = QtWidgets.QWidget(MatplotShow)
        self.plt_shower_widget.setObjectName("plt_shower_widget")
        self.gridLayout.addWidget(self.plt_shower_widget, 0, 0, 1, 1)

        self.retranslateUi(MatplotShow)
        QtCore.QMetaObject.connectSlotsByName(MatplotShow)

    def retranslateUi(self, MatplotShow):
        _translate = QtCore.QCoreApplication.translate
        MatplotShow.setWindowTitle(_translate("MatplotShow", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MatplotShow = QtWidgets.QWidget()
    ui = Ui_MatplotShow()
    ui.setupUi(MatplotShow)
    MatplotShow.show()
    sys.exit(app.exec_())
