# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raw_ui_files/phoneNumberParserScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_phoneNumberParser(object):
    def setupUi(self, phoneNumberParser):
        phoneNumberParser.setObjectName("phoneNumberParser")
        phoneNumberParser.resize(1009, 589)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mainLogo/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        phoneNumberParser.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(phoneNumberParser)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(phoneNumberParser)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 141))
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(70, 30, 151, 31))
        self.label.setStyleSheet("font: 11pt \"Hack\";")
        self.label.setObjectName("label")
        self.lineEdit_phoneInput = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_phoneInput.setGeometry(QtCore.QRect(240, 30, 451, 31))
        self.lineEdit_phoneInput.setStyleSheet("font: 11pt \"Hack\";")
        self.lineEdit_phoneInput.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_phoneInput.setObjectName("lineEdit_phoneInput")
        self.pushButton_startProccess = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_startProccess.setGeometry(QtCore.QRect(70, 90, 171, 31))
        self.pushButton_startProccess.setStyleSheet("font: 11pt \"Hack\";")
        self.pushButton_startProccess.setObjectName("pushButton_startProccess")
        self.pushButton_saveResults = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_saveResults.setGeometry(QtCore.QRect(270, 90, 171, 31))
        self.pushButton_saveResults.setStyleSheet("font: 11pt \"Hack\";")
        self.pushButton_saveResults.setObjectName("pushButton_saveResults")
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(phoneNumberParser)
        self.widget.setObjectName("widget")
        self.textBrowser_logConsole = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_logConsole.setGeometry(QtCore.QRect(20, 10, 971, 401))
        self.textBrowser_logConsole.setStyleSheet("font: 11pt \"Hack\";")
        self.textBrowser_logConsole.setObjectName("textBrowser_logConsole")
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 1)

        self.retranslateUi(phoneNumberParser)
        QtCore.QMetaObject.connectSlotsByName(phoneNumberParser)

    def retranslateUi(self, phoneNumberParser):
        _translate = QtCore.QCoreApplication.translate
        phoneNumberParser.setWindowTitle(_translate("phoneNumberParser", "Form"))
        self.label.setText(_translate("phoneNumberParser", "Enter number:"))
        self.pushButton_startProccess.setText(_translate("phoneNumberParser", "Start"))
        self.pushButton_saveResults.setText(_translate("phoneNumberParser", "Save Results"))
        self.textBrowser_logConsole.setHtml(_translate("phoneNumberParser", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Hack\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">LOG AND RESULTS:</span></p></body></html>"))
import main_icon_files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    phoneNumberParser = QtWidgets.QWidget()
    ui = Ui_phoneNumberParser()
    ui.setupUi(phoneNumberParser)
    phoneNumberParser.show()
    sys.exit(app.exec_())
