# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raw_ui_files/soundConverter.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SounConverter_widget(object):
    def setupUi(self, SounConverter_widget):
        SounConverter_widget.setObjectName("SounConverter_widget")
        SounConverter_widget.resize(1127, 660)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mainLogo/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SounConverter_widget.setWindowIcon(icon)
        SounConverter_widget.setStyleSheet("font: 11pt \"Hack\";")
        self.gridLayout_3 = QtWidgets.QGridLayout(SounConverter_widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(SounConverter_widget)
        self.label.setStyleSheet("font: 11pt \"Hack\";")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(SounConverter_widget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_soundConverter_selectTargetFormat = QtWidgets.QComboBox(self.widget)
        self.comboBox_soundConverter_selectTargetFormat.setMaximumSize(QtCore.QSize(141, 31))
        self.comboBox_soundConverter_selectTargetFormat.setStyleSheet("font: 11pt \"Hack\";")
        self.comboBox_soundConverter_selectTargetFormat.setObjectName("comboBox_soundConverter_selectTargetFormat")
        self.comboBox_soundConverter_selectTargetFormat.addItem("")
        self.comboBox_soundConverter_selectTargetFormat.addItem("")
        self.comboBox_soundConverter_selectTargetFormat.addItem("")
        self.comboBox_soundConverter_selectTargetFormat.addItem("")
        self.comboBox_soundConverter_selectTargetFormat.addItem("")
        self.comboBox_soundConverter_selectTargetFormat.addItem("")
        self.comboBox_soundConverter_selectTargetFormat.addItem("")
        self.comboBox_soundConverter_selectTargetFormat.addItem("")
        self.comboBox_soundConverter_selectTargetFormat.addItem("")
        self.comboBox_soundConverter_selectTargetFormat.addItem("")
        self.gridLayout.addWidget(self.comboBox_soundConverter_selectTargetFormat, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.pushButton_soundConverter_selectSoundFile = QtWidgets.QPushButton(self.widget)
        self.pushButton_soundConverter_selectSoundFile.setMaximumSize(QtCore.QSize(181, 41))
        self.pushButton_soundConverter_selectSoundFile.setStyleSheet("font: 11pt \"Hack\";")
        self.pushButton_soundConverter_selectSoundFile.setObjectName("pushButton_soundConverter_selectSoundFile")
        self.gridLayout.addWidget(self.pushButton_soundConverter_selectSoundFile, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMaximumSize(QtCore.QSize(141, 31))
        self.label_3.setStyleSheet("font: 11pt \"Hack\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setStyleSheet("font: 11pt \"Hack\";")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMaximumSize(QtCore.QSize(151, 31))
        self.label_2.setStyleSheet("font: 11pt \"Hack\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.pushButton_soundConverter_runConvert = QtWidgets.QPushButton(self.widget)
        self.pushButton_soundConverter_runConvert.setMaximumSize(QtCore.QSize(141, 41))
        self.pushButton_soundConverter_runConvert.setStyleSheet("font: 11pt \"Hack\";")
        self.pushButton_soundConverter_runConvert.setObjectName("pushButton_soundConverter_runConvert")
        self.gridLayout.addWidget(self.pushButton_soundConverter_runConvert, 4, 1, 1, 1)
        self.textBrowser_soundConverter_sourceFile_print = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_soundConverter_sourceFile_print.setMinimumSize(QtCore.QSize(571, 31))
        self.textBrowser_soundConverter_sourceFile_print.setMaximumSize(QtCore.QSize(571, 31))
        self.textBrowser_soundConverter_sourceFile_print.setStyleSheet("font: 11pt \"Hack\";")
        self.textBrowser_soundConverter_sourceFile_print.setObjectName("textBrowser_soundConverter_sourceFile_print")
        self.gridLayout.addWidget(self.textBrowser_soundConverter_sourceFile_print, 0, 1, 1, 1)
        self.lineEdit_soundConverter_outputName_input = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_soundConverter_outputName_input.setMinimumSize(QtCore.QSize(571, 31))
        self.lineEdit_soundConverter_outputName_input.setMaximumSize(QtCore.QSize(571, 31))
        self.lineEdit_soundConverter_outputName_input.setStyleSheet("font: 11pt \"Hack\";")
        self.lineEdit_soundConverter_outputName_input.setObjectName("lineEdit_soundConverter_outputName_input")
        self.gridLayout.addWidget(self.lineEdit_soundConverter_outputName_input, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.widget_2)
        self.textBrowser.setMinimumSize(QtCore.QSize(1091, 131))
        self.textBrowser.setMaximumSize(QtCore.QSize(1091, 131))
        self.textBrowser.setStyleSheet("font: 11pt \"Hack\";")
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 3, 0, 1, 1)
        self.textBrowser_soundConverter_logConsole = QtWidgets.QTextBrowser(self.widget_2)
        self.textBrowser_soundConverter_logConsole.setMinimumSize(QtCore.QSize(1091, 192))
        self.textBrowser_soundConverter_logConsole.setMaximumSize(QtCore.QSize(1091, 192))
        self.textBrowser_soundConverter_logConsole.setStyleSheet("font: 11pt \"Hack\";")
        self.textBrowser_soundConverter_logConsole.setObjectName("textBrowser_soundConverter_logConsole")
        self.gridLayout_2.addWidget(self.textBrowser_soundConverter_logConsole, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 4, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_2, 2, 0, 1, 1)

        self.retranslateUi(SounConverter_widget)
        QtCore.QMetaObject.connectSlotsByName(SounConverter_widget)

    def retranslateUi(self, SounConverter_widget):
        _translate = QtCore.QCoreApplication.translate
        SounConverter_widget.setWindowTitle(_translate("SounConverter_widget", "Form"))
        self.label.setText(_translate("SounConverter_widget", "<html><head/><body><p align=\"center\">Sound Converter</p></body></html>"))
        self.comboBox_soundConverter_selectTargetFormat.setItemText(0, _translate("SounConverter_widget", "mp3"))
        self.comboBox_soundConverter_selectTargetFormat.setItemText(1, _translate("SounConverter_widget", "m4a"))
        self.comboBox_soundConverter_selectTargetFormat.setItemText(2, _translate("SounConverter_widget", "wav"))
        self.comboBox_soundConverter_selectTargetFormat.setItemText(3, _translate("SounConverter_widget", "flac"))
        self.comboBox_soundConverter_selectTargetFormat.setItemText(4, _translate("SounConverter_widget", "opus"))
        self.comboBox_soundConverter_selectTargetFormat.setItemText(5, _translate("SounConverter_widget", "flac"))
        self.comboBox_soundConverter_selectTargetFormat.setItemText(6, _translate("SounConverter_widget", "ogg"))
        self.comboBox_soundConverter_selectTargetFormat.setItemText(7, _translate("SounConverter_widget", "aac"))
        self.comboBox_soundConverter_selectTargetFormat.setItemText(8, _translate("SounConverter_widget", "aiff"))
        self.comboBox_soundConverter_selectTargetFormat.setItemText(9, _translate("SounConverter_widget", "wma"))
        self.pushButton_soundConverter_selectSoundFile.setText(_translate("SounConverter_widget", "select file"))
        self.label_3.setText(_translate("SounConverter_widget", "Output Name:"))
        self.label_4.setText(_translate("SounConverter_widget", "Target Format:"))
        self.label_2.setText(_translate("SounConverter_widget", "Source File:"))
        self.pushButton_soundConverter_runConvert.setText(_translate("SounConverter_widget", "convert"))
        self.textBrowser.setHtml(_translate("SounConverter_widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Hack\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'FreeMono\'; font-size:14pt; font-weight:600; text-decoration: underline;\">SOUND CONVERTER:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'FreeMono\'; font-size:14pt; font-weight:600; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'FreeMono\'; font-size:14pt;\">Output Directory:  (exec_dir)/output</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'FreeMono\'; font-size:14pt;\">Supported Formats: </span><span style=\" font-family:\'Cantarell\';\">MP3, VAW, OPUS, FLAC, OGG, AAC, AIFF, WMA, M4A</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Cantarell\';\"><br /></p></body></html>"))
import main_icon_files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SounConverter_widget = QtWidgets.QWidget()
    ui = Ui_SounConverter_widget()
    ui.setupUi(SounConverter_widget)
    SounConverter_widget.show()
    sys.exit(app.exec_())
