# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raw_ui_files/TcNumberValidationCheckerScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TcValidatorScreen(object):
    def setupUi(self, TcValidatorScreen):
        TcValidatorScreen.setObjectName("TcValidatorScreen")
        TcValidatorScreen.resize(957, 648)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mainLogo/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TcValidatorScreen.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(TcValidatorScreen)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(TcValidatorScreen)
        self.label_2.setStyleSheet("font: 11pt \"Hack\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.pushButton_runValidationChecker = QtWidgets.QPushButton(TcValidatorScreen)
        self.pushButton_runValidationChecker.setMinimumSize(QtCore.QSize(131, 31))
        self.pushButton_runValidationChecker.setMaximumSize(QtCore.QSize(131, 31))
        self.pushButton_runValidationChecker.setStyleSheet("font: 11pt \"Hack\";")
        self.pushButton_runValidationChecker.setObjectName("pushButton_runValidationChecker")
        self.gridLayout.addWidget(self.pushButton_runValidationChecker, 1, 2, 1, 1)
        self.lineEdit_tcInput = QtWidgets.QLineEdit(TcValidatorScreen)
        self.lineEdit_tcInput.setMinimumSize(QtCore.QSize(591, 31))
        self.lineEdit_tcInput.setMaximumSize(QtCore.QSize(591, 31))
        self.lineEdit_tcInput.setObjectName("lineEdit_tcInput")
        self.gridLayout.addWidget(self.lineEdit_tcInput, 1, 1, 1, 1)
        self.textBrowser_logConsole = QtWidgets.QTextBrowser(TcValidatorScreen)
        self.textBrowser_logConsole.setObjectName("textBrowser_logConsole")
        self.gridLayout.addWidget(self.textBrowser_logConsole, 3, 0, 1, 3)
        self.label = QtWidgets.QLabel(TcValidatorScreen)
        self.label.setStyleSheet("font: 11pt \"Hack\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)

        self.retranslateUi(TcValidatorScreen)
        QtCore.QMetaObject.connectSlotsByName(TcValidatorScreen)

    def retranslateUi(self, TcValidatorScreen):
        _translate = QtCore.QCoreApplication.translate
        TcValidatorScreen.setWindowTitle(_translate("TcValidatorScreen", "Form"))
        self.label_2.setText(_translate("TcValidatorScreen", "Enter Tc Number:"))
        self.pushButton_runValidationChecker.setText(_translate("TcValidatorScreen", "Check"))
        self.textBrowser_logConsole.setHtml(_translate("TcValidatorScreen", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">LOG AND RESULTS:</span></p></body></html>"))
        self.label.setText(_translate("TcValidatorScreen", "<html><head/><body><p align=\"center\">TC Validator</p></body></html>"))
import main_icon_files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TcValidatorScreen = QtWidgets.QWidget()
    ui = Ui_TcValidatorScreen()
    ui.setupUi(TcValidatorScreen)
    TcValidatorScreen.show()
    sys.exit(app.exec_())
