# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raw_ui_files/TcNumberCalculatorScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TcNumberCalculator(object):
    def setupUi(self, TcNumberCalculator):
        TcNumberCalculator.setObjectName("TcNumberCalculator")
        TcNumberCalculator.resize(957, 648)
        self.gridLayout = QtWidgets.QGridLayout(TcNumberCalculator)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(TcNumberCalculator)
        self.label_3.setStyleSheet("font: 11pt \"Hack\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.pushButton_startCalculator = QtWidgets.QPushButton(TcNumberCalculator)
        self.pushButton_startCalculator.setMinimumSize(QtCore.QSize(131, 31))
        self.pushButton_startCalculator.setMaximumSize(QtCore.QSize(131, 31))
        self.pushButton_startCalculator.setStyleSheet("font: 11pt \"Hack\";")
        self.pushButton_startCalculator.setObjectName("pushButton_startCalculator")
        self.gridLayout.addWidget(self.pushButton_startCalculator, 2, 2, 1, 1)
        self.textBrowser_yasalBilgi = QtWidgets.QTextBrowser(TcNumberCalculator)
        self.textBrowser_yasalBilgi.setMaximumSize(QtCore.QSize(16777215, 71))
        self.textBrowser_yasalBilgi.setStyleSheet("font: 11pt \"Hack\";")
        self.textBrowser_yasalBilgi.setObjectName("textBrowser_yasalBilgi")
        self.gridLayout.addWidget(self.textBrowser_yasalBilgi, 6, 0, 1, 3)
        self.lineEdit_tcNumberInput = QtWidgets.QLineEdit(TcNumberCalculator)
        self.lineEdit_tcNumberInput.setMinimumSize(QtCore.QSize(591, 31))
        self.lineEdit_tcNumberInput.setMaximumSize(QtCore.QSize(591, 31))
        self.lineEdit_tcNumberInput.setObjectName("lineEdit_tcNumberInput")
        self.gridLayout.addWidget(self.lineEdit_tcNumberInput, 2, 1, 1, 1)
        self.textBrowser_logConsole = QtWidgets.QTextBrowser(TcNumberCalculator)
        self.textBrowser_logConsole.setObjectName("textBrowser_logConsole")
        self.gridLayout.addWidget(self.textBrowser_logConsole, 5, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(TcNumberCalculator)
        self.label_2.setStyleSheet("font: 11pt \"Hack\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.spinBox_numberOfCalculating = QtWidgets.QSpinBox(TcNumberCalculator)
        self.spinBox_numberOfCalculating.setMaximumSize(QtCore.QSize(205, 27))
        self.spinBox_numberOfCalculating.setDisplayIntegerBase(10)
        self.spinBox_numberOfCalculating.setObjectName("spinBox_numberOfCalculating")
        self.gridLayout.addWidget(self.spinBox_numberOfCalculating, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(TcNumberCalculator)
        self.label.setStyleSheet("font: 11pt \"Hack\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)

        self.retranslateUi(TcNumberCalculator)
        QtCore.QMetaObject.connectSlotsByName(TcNumberCalculator)

    def retranslateUi(self, TcNumberCalculator):
        _translate = QtCore.QCoreApplication.translate
        TcNumberCalculator.setWindowTitle(_translate("TcNumberCalculator", "Form"))
        self.label_3.setText(_translate("TcNumberCalculator", "Hesaplama adeti:"))
        self.pushButton_startCalculator.setText(_translate("TcNumberCalculator", "Calculate"))
        self.textBrowser_yasalBilgi.setHtml(_translate("TcNumberCalculator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Hack\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\';\">Bir kişinin TC numarası rastgele atanmaz, anne ve babasının tc numarasına göre matematiksel olarak atanır bu sistemde bunu kullanarak geçmiş ve gelecekte atanmış / atanabilecek TC numaralarını hesaplamaya çalışır. Python matematik eğitimi içindir herhangi bir işlemden yasal olarak yazar sorumlu tutulamaz!</span></p></body></html>"))
        self.textBrowser_logConsole.setHtml(_translate("TcNumberCalculator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">LOG AND RESULTS:</span></p></body></html>"))
        self.label_2.setText(_translate("TcNumberCalculator", "Enter Tc Number:"))
        self.label.setText(_translate("TcNumberCalculator", "<html><head/><body><p align=\"center\">TC Calculator</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TcNumberCalculator = QtWidgets.QWidget()
    ui = Ui_TcNumberCalculator()
    ui.setupUi(TcNumberCalculator)
    TcNumberCalculator.show()
    sys.exit(app.exec_())
