# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raw_ui_files/TheHive_mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TheHve_MainWindow(object):
    def setupUi(self, TheHve_MainWindow):
        TheHve_MainWindow.setObjectName("TheHve_MainWindow")
        TheHve_MainWindow.resize(967, 656)
        self.centralwidget = QtWidgets.QWidget(TheHve_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textBrowser_WelcomeAndToolinfo = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_WelcomeAndToolinfo.setObjectName("textBrowser_WelcomeAndToolinfo")
        self.gridLayout_2.addWidget(self.textBrowser_WelcomeAndToolinfo, 0, 0, 1, 1)
        self.textBrowser_systemStatus = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_systemStatus.setObjectName("textBrowser_systemStatus")
        self.gridLayout_2.addWidget(self.textBrowser_systemStatus, 2, 0, 1, 1)
        self.line_coolBar_tab_1 = QtWidgets.QFrame(self.tab)
        self.line_coolBar_tab_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_coolBar_tab_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_coolBar_tab_1.setObjectName("line_coolBar_tab_1")
        self.gridLayout_2.addWidget(self.line_coolBar_tab_1, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        TheHve_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar_menuController = QtWidgets.QMenuBar(TheHve_MainWindow)
        self.menubar_menuController.setGeometry(QtCore.QRect(0, 0, 967, 24))
        self.menubar_menuController.setObjectName("menubar_menuController")
        self.menuSecurity = QtWidgets.QMenu(self.menubar_menuController)
        self.menuSecurity.setObjectName("menuSecurity")
        self.menuOsintTools = QtWidgets.QMenu(self.menubar_menuController)
        self.menuOsintTools.setObjectName("menuOsintTools")
        TheHve_MainWindow.setMenuBar(self.menubar_menuController)
        self.statusbar = QtWidgets.QStatusBar(TheHve_MainWindow)
        self.statusbar.setObjectName("statusbar")
        TheHve_MainWindow.setStatusBar(self.statusbar)
        self.actionChange_Login_Password = QtWidgets.QAction(TheHve_MainWindow)
        self.actionChange_Login_Password.setObjectName("actionChange_Login_Password")
        self.menuSecurity.addAction(self.actionChange_Login_Password)
        self.menubar_menuController.addAction(self.menuSecurity.menuAction())
        self.menubar_menuController.addAction(self.menuOsintTools.menuAction())

        self.retranslateUi(TheHve_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(TheHve_MainWindow)

    def retranslateUi(self, TheHve_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        TheHve_MainWindow.setWindowTitle(_translate("TheHve_MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("TheHve_MainWindow", "Welcome"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("TheHve_MainWindow", "Tab 2"))
        self.menuSecurity.setTitle(_translate("TheHve_MainWindow", "Security"))
        self.menuOsintTools.setTitle(_translate("TheHve_MainWindow", "Osint Tools"))
        self.actionChange_Login_Password.setText(_translate("TheHve_MainWindow", "Change Login Password"))
import main_icon_files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TheHve_MainWindow = QtWidgets.QMainWindow()
    ui = Ui_TheHve_MainWindow()
    ui.setupUi(TheHve_MainWindow)
    TheHve_MainWindow.show()
    sys.exit(app.exec_())
