# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raw_ui_files/soundVerification.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_voiceVerificationWidget(object):
    def setupUi(self, voiceVerificationWidget):
        voiceVerificationWidget.setObjectName("voiceVerificationWidget")
        voiceVerificationWidget.resize(978, 520)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mainLogo/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        voiceVerificationWidget.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(voiceVerificationWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_mainWidget = QtWidgets.QWidget(voiceVerificationWidget)
        self.widget_mainWidget.setObjectName("widget_mainWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_mainWidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_inputArea = QtWidgets.QWidget(self.widget_mainWidget)
        self.widget_inputArea.setObjectName("widget_inputArea")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_inputArea)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_selectFile1 = QtWidgets.QPushButton(self.widget_inputArea)
        self.pushButton_selectFile1.setStyleSheet("font: 11pt \"Hack\";")
        self.pushButton_selectFile1.setObjectName("pushButton_selectFile1")
        self.gridLayout.addWidget(self.pushButton_selectFile1, 0, 2, 1, 1)
        self.pushButton_runComparsion = QtWidgets.QPushButton(self.widget_inputArea)
        self.pushButton_runComparsion.setStyleSheet("font: 11pt \"Hack\";")
        self.pushButton_runComparsion.setObjectName("pushButton_runComparsion")
        self.gridLayout.addWidget(self.pushButton_runComparsion, 1, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_inputArea)
        self.label.setStyleSheet("font: 11pt \"Hack\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_selectFile2 = QtWidgets.QPushButton(self.widget_inputArea)
        self.pushButton_selectFile2.setStyleSheet("font: 11pt \"Hack\";")
        self.pushButton_selectFile2.setObjectName("pushButton_selectFile2")
        self.gridLayout.addWidget(self.pushButton_selectFile2, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_inputArea)
        self.label_2.setStyleSheet("font: 11pt \"Hack\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 1)
        self.textBrowser_voice1showPath = QtWidgets.QTextBrowser(self.widget_inputArea)
        self.textBrowser_voice1showPath.setMinimumSize(QtCore.QSize(511, 31))
        self.textBrowser_voice1showPath.setMaximumSize(QtCore.QSize(601, 31))
        self.textBrowser_voice1showPath.setStyleSheet("font: 11pt \"Hack\";")
        self.textBrowser_voice1showPath.setObjectName("textBrowser_voice1showPath")
        self.gridLayout.addWidget(self.textBrowser_voice1showPath, 0, 1, 1, 1)
        self.pushButton_saveResults = QtWidgets.QPushButton(self.widget_inputArea)
        self.pushButton_saveResults.setStyleSheet("font: 11pt \"Hack\";")
        self.pushButton_saveResults.setObjectName("pushButton_saveResults")
        self.gridLayout.addWidget(self.pushButton_saveResults, 0, 4, 1, 1)
        self.textBrowser_voice2showPath = QtWidgets.QTextBrowser(self.widget_inputArea)
        self.textBrowser_voice2showPath.setMinimumSize(QtCore.QSize(511, 31))
        self.textBrowser_voice2showPath.setMaximumSize(QtCore.QSize(601, 31))
        self.textBrowser_voice2showPath.setStyleSheet("font: 11pt \"Hack\";")
        self.textBrowser_voice2showPath.setObjectName("textBrowser_voice2showPath")
        self.gridLayout.addWidget(self.textBrowser_voice2showPath, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 5, 1, 1)
        self.gridLayout_4.addWidget(self.widget_inputArea, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 4, 0, 1, 1)
        self.widget_3_similarityProgressBar = QtWidgets.QWidget(self.widget_mainWidget)
        self.widget_3_similarityProgressBar.setObjectName("widget_3_similarityProgressBar")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_3_similarityProgressBar)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem4, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_3_similarityProgressBar)
        self.label_3.setStyleSheet("font: 11pt \"Hack\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 2)
        self.progressBar_similarityShower = QtWidgets.QProgressBar(self.widget_3_similarityProgressBar)
        self.progressBar_similarityShower.setMaximumSize(QtCore.QSize(681, 31))
        self.progressBar_similarityShower.setStyleSheet("font: 11pt \"Hack\";")
        self.progressBar_similarityShower.setProperty("value", 0)
        self.progressBar_similarityShower.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_similarityShower.setInvertedAppearance(False)
        self.progressBar_similarityShower.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_similarityShower.setObjectName("progressBar_similarityShower")
        self.gridLayout_5.addWidget(self.progressBar_similarityShower, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_3_similarityProgressBar, 5, 0, 1, 1)
        self.textBrowser_logAndResults = QtWidgets.QTextBrowser(self.widget_mainWidget)
        self.textBrowser_logAndResults.setStyleSheet("font: 11pt \"Hack\";")
        self.textBrowser_logAndResults.setObjectName("textBrowser_logAndResults")
        self.gridLayout_4.addWidget(self.textBrowser_logAndResults, 3, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.widget_mainWidget)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setStyleSheet("font: 11pt \"Hack\";")
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_4, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget_mainWidget, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 3, 0, 1, 1)

        self.retranslateUi(voiceVerificationWidget)
        QtCore.QMetaObject.connectSlotsByName(voiceVerificationWidget)

    def retranslateUi(self, voiceVerificationWidget):
        _translate = QtCore.QCoreApplication.translate
        voiceVerificationWidget.setWindowTitle(_translate("voiceVerificationWidget", "Form"))
        self.pushButton_selectFile1.setText(_translate("voiceVerificationWidget", "select file 1"))
        self.pushButton_runComparsion.setText(_translate("voiceVerificationWidget", "compare"))
        self.label.setText(_translate("voiceVerificationWidget", "Voice 1:"))
        self.pushButton_selectFile2.setText(_translate("voiceVerificationWidget", "select file 2"))
        self.label_2.setText(_translate("voiceVerificationWidget", "Voice 2:"))
        self.pushButton_saveResults.setText(_translate("voiceVerificationWidget", "save result"))
        self.label_3.setText(_translate("voiceVerificationWidget", "similarity ratio:"))
        self.progressBar_similarityShower.setFormat(_translate("voiceVerificationWidget", "%%p"))
        self.textBrowser_logAndResults.setHtml(_translate("voiceVerificationWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Hack\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\'; font-weight:600;\">LOG AND RESULTS:</span></p></body></html>"))
        self.label_4.setText(_translate("voiceVerificationWidget", "<html><head/><body><p align=\"center\">Voice Verification</p></body></html>"))
import main_icon_files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    voiceVerificationWidget = QtWidgets.QWidget()
    ui = Ui_voiceVerificationWidget()
    ui.setupUi(voiceVerificationWidget)
    voiceVerificationWidget.show()
    sys.exit(app.exec_())
